gpus: 1
s3: True
batch_size: 8
max_epochs: 50
num_sanity_val_steps: 0
patience: 3
batch_norm: False
fp_data: True

optimizer_params:
  optimizer: Adam
  lr: 0.001

scheduler_params:
  scheduler: OneCycleLR
  interval: step
  max_lr: 0.0001
  steps_per_epoch: 204
  epochs: 500
  pct_start: 0.1
