s3: True
batch_size: 16
max_epochs: 100
num_sanity_val_steps: 1
patience: 5
batch_norm: False
fp_data: True

optimizer_params:
  optimizer: Adam
  lr: 0.0001

scheduler_params:
  scheduler: ReduceLROnPlateau
  interval: epoch
  patience: 3
