s3: True
batch_size: 8
max_epochs: 300
num_sanity_val_steps: 2
patience: 30
batch_norm: False
fp_data: False

optimizer_params:
  optimizer: Adam
  lr: 0.001

scheduler_params:
  scheduler: OneCycleLR
  interval: step
  max_lr: 0.0001
  steps_per_epoch: 58
  epochs: 300
  pct_start: 0.1
